// Member-facing Notification Center (Community & Commerce track, item
// 11), mounted at /notifications. Every signed-in portal account has
// its own notification history here, generated by utils/notifications.js's
// notify() - never hand-entered. /notifications/preferences is a
// member's own per-type email/sms opt-out (in-app can't be turned off -
// see the migration's own comment on notification_preferences).
const express = require('express');
const router = express.Router();
const { requirePortalAuth } = require('../middleware/portalAuth');
const notifications = require('../utils/notifications');

router.use(requirePortalAuth);

router.get('/', async (req, res) => {
  const items = await notifications.listForAccount(req.portalAccount.id);
  res.render('notifications-list', { title: 'Notifications', items });
});

router.post('/:id/read', async (req, res) => {
  await notifications.markRead(req.portalAccount.id, req.params.id);
  res.redirect(req.get('Referer') || '/notifications');
});

router.post('/read-all', async (req, res) => {
  await notifications.markAllRead(req.portalAccount.id);
  res.redirect('/notifications');
});

router.get('/preferences', async (req, res) => {
  const preferences = await notifications.preferencesForAccount(req.portalAccount.id);
  res.render('notifications-preferences', { title: 'Notification Preferences', preferences, notice: req.query.notice || null });
});

router.post('/preferences', async (req, res) => {
  const types = await notifications.listTypes();
  for (const type of types) {
    await notifications.setPreference(req.portalAccount.id, type.key, 'email', req.body[`email_${type.key}`] === '1');
    await notifications.setPreference(req.portalAccount.id, type.key, 'sms', req.body[`sms_${type.key}`] === '1');
  }
  res.redirect('/notifications/preferences?notice=' + encodeURIComponent('Saved.'));
});

module.exports = router;
